// Generates every brand asset from one definition: the logo data used by
// <Logo/>, standalone SVGs, favicon/app icons and the social share image.
//
//   npm run brand
//
// Needs the dev dependencies `opentype.js` and `sharp`. Fonts live in
// scripts/brand/fonts (both SIL OFL): Outfit for the Latin wordmark (turned
// into outlines, so the app needs no font for it) and Vazirmatn for the
// Persian text in the share image.

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = path.join(root, "scripts/brand/fonts");

// librsvg (inside sharp) finds fonts through fontconfig: point it at our folder
// so the result doesn't depend on what is installed on this machine.
if (!process.env.MATRISS_FC) {
  const conf = path.join(root, "node_modules/.cache/matriss-fonts.conf");
  fs.mkdirSync(path.dirname(conf), { recursive: true });
  fs.writeFileSync(
    conf,
    `<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>${fontsDir}</dir><cachedir>${path.join(
      root,
      "node_modules/.cache/fontconfig",
    )}</cachedir></fontconfig>`,
  );
  const r = spawnSync(process.execPath, [fileURLToPath(import.meta.url)], {
    stdio: "inherit",
    env: { ...process.env, MATRISS_FC: "1", FONTCONFIG_FILE: conf },
  });
  process.exit(r.status ?? 1);
}

const { default: opentype } = await import("opentype.js");
const { default: sharp } = await import("sharp");

const NAVY = "#0f2d58";
const YELLOW = "#fdd365";
const BLUE_LIGHT = "#a7cfff";

// ---- the mark: an M that climbs to a goal dot (64×64 grid) ----
const markShapes = (ink, accent) =>
  `<path d="M10 52V16l22 24 22-24v30" fill="none" stroke="${ink}" stroke-width="7.5" stroke-linecap="round" stroke-linejoin="round"/>` +
  `<circle cx="54" cy="12" r="6.2" fill="${accent}"/>`;

// ---- the wordmark: Outfit 600, as outlines in font units ----
const fontBuf = fs.readFileSync(path.join(fontsDir, "outfit-600.woff"));
const font = opentype.parse(
  fontBuf.buffer.slice(
    fontBuf.byteOffset,
    fontBuf.byteOffset + fontBuf.byteLength,
  ),
);
const U = font.unitsPerEm;
let cx = 0;
let wordD = "";
for (const ch of "Matriss") {
  const g = font.charToGlyph(ch);
  wordD += g.getPath(cx, 0, U).toPathData(1);
  cx += g.advanceWidth;
}
const WORD_WIDTH_UNITS = cx; // advance in font units
const WORD_SIZE = 64; // drawn at 64 on the mark's grid
const wordScale = WORD_SIZE / U;
const WORD_X = 76; // gap after the mark
const WORD_BASELINE = 46;
const lockupWidth = Math.round(WORD_X + WORD_WIDTH_UNITS * wordScale);

const lockup = (ink, accent) =>
  `${markShapes(ink, accent)}<path transform="translate(${WORD_X},${WORD_BASELINE}) scale(${wordScale})" d="${wordD}" fill="${ink}"/>`;

const svgDoc = (inner, w, h, vb) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${vb}">${inner}</svg>`;

const write = (rel, data) => {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, data);
  console.log("wrote", rel);
};

// ---- 1. data for the <Logo/> component ----
write(
  "src/components/brand/logo-data.ts",
  `// Generated by scripts/generate-brand.mjs — do not edit by hand.\n` +
    `export const MARK_STROKE_PATH = "M10 52V16l22 24 22-24v30";\n` +
    `export const WORDMARK_PATH = "${wordD}";\n` +
    `export const WORDMARK_SCALE = ${wordScale};\n` +
    `export const WORDMARK_X = ${WORD_X};\n` +
    `export const WORDMARK_BASELINE = ${WORD_BASELINE};\n` +
    `export const LOCKUP_WIDTH = ${lockupWidth};\n`,
);

// ---- 2. standalone SVGs ----
write(
  "public/brand/mark.svg",
  svgDoc(markShapes(NAVY, YELLOW), 64, 64, "0 0 64 64"),
);
write(
  "public/brand/logo.svg",
  svgDoc(lockup(NAVY, YELLOW), lockupWidth, 64, `0 0 ${lockupWidth} 64`),
);
write(
  "public/brand/logo-white.svg",
  svgDoc(lockup("#ffffff", YELLOW), lockupWidth, 64, `0 0 ${lockupWidth} 64`),
);

// ---- 3. icons: the mark, white on navy ----
const iconSvg = (size, { pad = 0.16, radius = 0.22, bleed = false } = {}) => {
  const inner = size * (1 - pad * 2);
  const off = size * pad;
  return svgDoc(
    `<rect width="${size}" height="${size}" rx="${bleed ? 0 : size * radius}" fill="${NAVY}"/>` +
      `<g transform="translate(${off},${off}) scale(${inner / 64})">${markShapes("#ffffff", YELLOW)}</g>`,
    size,
    size,
    `0 0 ${size} ${size}`,
  );
};
write("src/app/icon.svg", iconSvg(64, { pad: 0.12 }));
const png = async (rel, svg, size) => {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  await sharp(Buffer.from(svg), { density: 384 })
    .resize(size, size)
    .png()
    .toFile(file);
  console.log("wrote", rel);
};
await png(
  "src/app/apple-icon.png",
  iconSvg(180, { pad: 0.16, bleed: true }),
  180,
);
await png("public/icons/icon-192.png", iconSvg(192, { pad: 0.14 }), 192);
await png("public/icons/icon-512.png", iconSvg(512, { pad: 0.14 }), 512);
// Maskable icons are cropped into any shape: keep the art inside the safe 80% circle.
await png(
  "public/icons/icon-maskable-512.png",
  iconSvg(512, { pad: 0.22, bleed: true }),
  512,
);

// favicon.ico: PNGs of 16/32/48 packed into one ICO container (browsers that
// ignore icon.svg, bookmarks and old crawlers still ask for /favicon.ico).
{
  const sizes = [16, 32, 48];
  const pngs = [];
  for (const sz of sizes)
    pngs.push(
      await sharp(Buffer.from(iconSvg(sz * 8, { pad: 0.1, radius: 0.22 })), {
        density: 72,
      })
        .resize(sz, sz)
        .png()
        .toBuffer(),
    );
  const head = Buffer.alloc(6);
  head.writeUInt16LE(1, 2); // type: icon
  head.writeUInt16LE(sizes.length, 4);
  let offset = 6 + 16 * sizes.length;
  const dirs = pngs.map((b, i) => {
    const d = Buffer.alloc(16);
    d.writeUInt8(sizes[i], 0);
    d.writeUInt8(sizes[i], 1);
    d.writeUInt16LE(1, 4); // planes
    d.writeUInt16LE(32, 6); // bits per pixel
    d.writeUInt32LE(b.length, 8);
    d.writeUInt32LE(offset, 12);
    offset += b.length;
    return d;
  });
  const file = path.join(root, "src/app/favicon.ico");
  fs.writeFileSync(file, Buffer.concat([head, ...dirs, ...pngs]));
  console.log("wrote src/app/favicon.ico");
}

// ---- 4. social share image (1200×630) ----
const W = 1200,
  H = 630;
const og = (line1, line2, sub) =>
  svgDoc(
    `<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0f2d58"/><stop offset="1" stop-color="#0a1f3f"/></linearGradient></defs>` +
      `<rect width="${W}" height="${H}" fill="url(#g)"/>` +
      `<circle cx="150" cy="560" r="260" fill="#1d5fd6" opacity="0.22"/>` +
      `<circle cx="1040" cy="-10" r="170" fill="${YELLOW}" opacity="0.07"/>` +
      `<g transform="translate(${W - 60 - lockupWidth * 1.15},56) scale(1.15)">${lockup("#ffffff", YELLOW)}</g>` +
      `<g direction="rtl" text-anchor="start" font-family="Vazirmatn">` +
      `<text x="${W - 64}" y="300" font-size="76" font-weight="700" fill="#ffffff">${line1}</text>` +
      `<text x="${W - 64}" y="398" font-size="76" font-weight="700" fill="#ffffff">${line2}</text>` +
      `<text x="${W - 64}" y="486" font-size="34" font-weight="500" fill="${BLUE_LIGHT}">${sub}</text>` +
      `</g>` +
      `<rect x="${W - 64 - 120}" y="526" width="120" height="8" rx="4" fill="${YELLOW}"/>`,
    W,
    H,
    `0 0 ${W} ${H}`,
  );
const ogSvg = og(
  "مشاورت رو خودت انتخاب کن،",
  "از بین رتبه‌برترهای کنکور.",
  "رتبه‌ی همه‌ی مشاورها با کارنامه احراز شده · جلسه‌ی آشنایی رایگان",
);
for (const name of ["opengraph-image", "twitter-image"]) {
  const file = path.join(root, `src/app/${name}.png`);
  await sharp(Buffer.from(ogSvg)).png({ compressionLevel: 9 }).toFile(file);
  console.log("wrote", `src/app/${name}.png`);
}
write(
  "src/app/opengraph-image.alt.txt",
  "Matriss — مشاورت رو خودت انتخاب کن، از بین رتبه‌برترهای کنکور",
);
write(
  "src/app/twitter-image.alt.txt",
  "Matriss — مشاورت رو خودت انتخاب کن، از بین رتبه‌برترهای کنکور",
);
